[package]
name = "galgath"
version = "0.0.1"
edition = "2021"

[dependencies]
crowbook = "0.16.1"
reqwest = { version = "0.11.24", features = ["json"] }
serde_json = "1.0.114"
tokio = { version = "1", features = ["full"] }
url = "2.5.0"
